version: '3.7'

services:
  backend:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8080
    ports:
      - '8080:8080'
    env_file:
      - .env.docker
    networks: ['meetups_backend_network']
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks: ['meetups_backend_network']
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=meetups_db

volumes:
  postgres_data:

networks: {meetups_backend_network: {}}